""" ajout de la posologie

Revision ID: 10189dfa942e
Revises: f7e91f37f669
Create Date: 2025-02-08 21:57:51.779249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10189dfa942e'
down_revision = 'f7e91f37f669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posologie', sa.Text(), nullable=True))
        batch_op.drop_column('dosage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosage', sa.TEXT(), nullable=True))
        batch_op.drop_column('posologie')

    # ### end Alembic commands ###
