"""Recreatedeux colonne pour remedes

Revision ID: 1e2f4bede3cd
Revises: 
Create Date: 2025-01-24 18:53:18.335930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2f4bede3cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_inscription', sa.Date(), nullable=True))

    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('date_inscription')

    # ### end Alembic commands ###
