"""Recreatedeux colonne pour remedes

Revision ID: 4f72af6d5f70
Revises: f5c0f080c640
Create Date: 2025-01-25 03:38:41.145779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f72af6d5f70'
down_revision = 'f5c0f080c640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_nom_partie', ['nom_scientifique', 'partie'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nom_partie', type_='unique')

    # ### end Alembic commands ###
