""" ajout de la pdf

Revision ID: 5edfdd3490e4
Revises: 10189dfa942e
Create Date: 2025-02-24 15:47:18.397182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edfdd3490e4'
down_revision = '10189dfa942e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.drop_column('pdf')

    # ### end Alembic commands ###
