"""Recreatedeux bgb uy

Revision ID: 99bca81b8538
Revises: ce0714eabc96
Create Date: 2025-02-01 14:40:10.634106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bca81b8538'
down_revision = 'ce0714eabc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nom_partie', type_='unique')
        batch_op.create_unique_constraint('unique_nom_scientifique_partie', ['nom_scientifique', 'partie'])

    with op.batch_alter_table('maladie', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nom_partie', type_='unique')
        batch_op.create_unique_constraint('unique_nom_commun_maladie', ['nom_commun'])

    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nom_partie', type_='unique')
        batch_op.create_unique_constraint('unique_nom_remede', ['nom'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remedes', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nom_remede', type_='unique')
        batch_op.create_unique_constraint('unique_nom_partie', ['nom'])

    with op.batch_alter_table('maladie', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nom_commun_maladie', type_='unique')
        batch_op.create_unique_constraint('unique_nom_partie', ['nom_commun'])

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('unique_nom_scientifique_partie', type_='unique')
        batch_op.create_unique_constraint('unique_nom_partie', ['nom_scientifique', 'partie'])

    # ### end Alembic commands ###
