"""Recreatedeux bgb

Revision ID: ce0714eabc96
Revises: 8625fae9b325
Create Date: 2025-01-27 07:12:01.018109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0714eabc96'
down_revision = '8625fae9b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('remede_ingredient_articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remede_ingredient_articles',
    sa.Column('remede_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['remede_id'], ['remedes.id'], ),
    sa.PrimaryKeyConstraint('remede_id', 'ingredient_id', 'article_id')
    )
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('like', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('titre', sa.VARCHAR(length=255), nullable=False),
    sa.Column('auteur', sa.TEXT(), nullable=True),
    sa.Column('pdf', sa.VARCHAR(length=255), nullable=True),
    sa.Column('doi', sa.VARCHAR(length=255), nullable=True),
    sa.Column('liens', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_ajout', sa.DATE(), nullable=True),
    sa.Column('date_mise_a_jour', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titre', 'auteur', name='unique_titre_auteur')
    )
    # ### end Alembic commands ###
