"""Ajout de la table commentaire

Revision ID: f7e91f37f669
Revises: 99bca81b8538
Create Date: 2025-02-05 06:58:58.896882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e91f37f669'
down_revision = '99bca81b8538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.alter_column('remede_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('like')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like', sa.INTEGER(), nullable=True))
        batch_op.alter_column('remede_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
